version: '3.5'

#networks:
#  milvus_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.98.55.0/24
#          gateway: 172.98.55.1

networks:
  default:
    name: milvus

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.8.2
    restart: unless-stopped
    environment:
      # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
      # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/pulsar:/pulsar/data
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rootcoord:
    container_name: milvus-rootcoord
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "rootcoord"]
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  proxy:
    container_name: milvus-proxy
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "proxy"]
    ports:
      - "19530:19530"

  querycoord:
    container_name: milvus-querycoord
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "querycoord"]
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  querynode:
    container_name: milvus-querynode
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "querynode"]
    depends_on:
      - "querycoord"

  indexcoord:
    container_name: milvus-indexcoord
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "indexcoord"]
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  indexnode:
    container_name: milvus-indexnode
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "indexnode"]
    depends_on:
      - "indexcoord"

  datacoord:
    container_name: milvus-datacoord
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "datacoord"]
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"

  datanode:
    container_name: milvus-datanode
    image: milvusdb/milvus:${STACK_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    command: ["milvus", "run", "datanode"]
    depends_on:
      - "datacoord"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3434:3000"