version: '3'

networks:
  neo4j_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.95.0.0/24
          gateway: 10.95.0.1

services:

  neo4j-01:
    hostname: neo4j-01
    image: neo4j:5.14-enterprise
    networks:
      neo4j_cluster_net:
        ipv4_address: 10.95.0.2
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    volumes:
      - ./data/neo4j-neo4j-01/data:/data
      - ./data/neo4j-neo4j-01/metrics:/metrics
      - ./data/neo4j-neo4j-01/plugins:/plugins
      - ./data/neo4j-neo4j-01/import:/import
      - ./logs/neo4j-neo4j-01/logs:/logs
      - ./conf/neo4j-neo4j-01/conf:/conf
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=neo4j-01
      - NEO4J_server_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-01:5000,neo4j-02:5000,neo4j-03:5000,neo4j-04:5000
      - NEO4J_initial_server_tags=uneven
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*

  neo4j-02:
    hostname: neo4j-02
    image: neo4j:5.14-enterprise
    networks:
      neo4j_cluster_net:
        ipv4_address: 10.95.0.3
    ports:
      - "27474:7474"
      - "26477:6477"
      - "27687:7687"
    volumes:
      - ./data/neo4j-neo4j-02/data:/data
      - ./data/neo4j-neo4j-02/metrics:/metrics
      - ./data/neo4j-neo4j-02/plugins:/plugins
      - ./data/neo4j-neo4j-02/import:/import
      - ./logs/neo4j-neo4j-02/logs:/logs
      - ./conf/neo4j-neo4j-02/conf:/conf
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=neo4j-02
      - NEO4J_server_bolt_advertised__address=localhost:27687
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-01:5000,neo4j-02:5000,neo4j-03:5000,neo4j-04:5000
      - NEO4J_initial_server_tags=even
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*

  neo4j-03:
    hostname: neo4j-03
    image: neo4j:5.14-enterprise
    networks:
      neo4j_cluster_net:
        ipv4_address: 10.95.0.4
    ports:
      - "37474:7474"
      - "36477:6477"
      - "37687:7687"
    volumes:
      - ./data/neo4j-neo4j-03/data:/data
      - ./data/neo4j-neo4j-03/metrics:/metrics
      - ./data/neo4j-neo4j-03/plugins:/plugins
      - ./data/neo4j-neo4j-03/import:/import
      - ./logs/neo4j-neo4j-03/logs:/logs
      - ./conf/neo4j-neo4j-03/conf:/conf
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=neo4j-03
      - NEO4J_server_bolt_advertised__address=localhost:37687
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-01:5000,neo4j-02:5000,neo4j-03:5000,neo4j-04:5000
      - NEO4J_initial_server_tags=uneven
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*

  neo4j-04:
    hostname: neo4j-04
    image: neo4j:5.14-enterprise
    networks:
      neo4j_cluster_net:
        ipv4_address: 10.95.0.5
    ports:
      - "47474:7474"
      - "46477:6477"
      - "47687:7687"
    volumes:
      - ./data/neo4j-neo4j-04/data:/data
      - ./data/neo4j-neo4j-04/metrics:/metrics
      - ./data/neo4j-neo4j-04/plugins:/plugins
      - ./data/neo4j-neo4j-04/import:/import
      - ./logs/neo4j-neo4j-04/logs:/logs
      - ./conf/neo4j-neo4j-04/conf:/conf
    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=neo4j-04
      - NEO4J_server_bolt_advertised__address=localhost:47687
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-01:5000,neo4j-02:5000,neo4j-03:5000,neo4j-04:5000
      - NEO4J_initial_server_tags=even
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*

  secondary1:
    hostname: secondary1
    image: neo4j:5.14-enterprise
    networks:
      neo4j_cluster_net:
        ipv4_address: 10.95.0.6
    ports:
      - "57474:7474"
      - "56477:6477"
      - "57687:7687"
    volumes:
      - ./data/neo4j-secondary1/data:/data
      - ./data/neo4j-secondary1/metrics:/metrics
      - ./data/neo4j-secondary1/plugins:/plugins
      - ./data/neo4j-secondary1/import:/import
      - ./logs/neo4j-secondary1/logs:/logs
      - ./conf/neo4j-secondary1/conf:/conf

    environment:
      - NEO4J_AUTH=none
      - NEO4J_initial_server_mode__constraint=SECONDARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_default__advertised__address=secondary1
      - NEO4J_server_bolt_advertised__address=localhost:57687
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j-01:5000,neo4j-02:5000,neo4j-03:5000,neo4j-04:5000
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
