version: '3.7'

# configuration source https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  restart: unless-stopped
  expose:
    - "${MINIO_ADDRESS_PORT:-9000}"
    - "${MINIO_CONSOLE_PORT:-9001}"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    MINIO_PROMETHEUS_URL: ${MINIO_PROMETHEUS_URL:-http://prometheus:9090}
    MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
    #MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
    #MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    #MINIO_CACHE: "on"
    #MINIO_CACHE_DRIVES: /mnt/drive1,/mnt/drive2
    #MINIO_CACHE_QUOTA: 80 # 80% of the drive will be used for caching
    #MINIO_CACHE_AFTER: 1 # Object will be cached after the first request to it
    #MINIO_CACHE_WATERMARK_LOW: 70 # Least accessed objects will be erased after the cache disk reaches the 70% watermark
    #MINIO_CACHE_WATERMARK_HIGH: 90
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - minio-data1-1:/data1
      - minio-data1-2:/data2
    networks:
      mlops_network:

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - minio-data2-1:/data1
      - minio-data2-2:/data2
    networks:
      mlops_network:

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - minio-data3-1:/data1
      - minio-data3-2:/data2
    networks:
      mlops_network:

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - minio-data4-1:/data1
      - minio-data4-2:/data2
    networks:
      mlops_network:

  # Load Balancer
  nginx:
    image: nginx:1.19.2-alpine
    container_name: minio-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Add your MLOps Ports for nginx reverse proxy
    ports:
      - "${MINIO_ADDRESS_PORT:-9000}:80"
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
      # - "80:80"
    networks:
      mlops_network:
        ipv4_address: 172.48.0.50   # Replace with your desired static IP address for LB

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-data1-1:
  minio-data1-2:
  minio-data2-1:
  minio-data2-2:
  minio-data3-1:
  minio-data3-2:
  minio-data4-1:
  minio-data4-2:


networks:
  mlops_network:
    external: true