storage:
  storage_path: ./storage
  snapshots_path: ./snapshots
  on_disk_payload: true

  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0

  node_type: "Normal"

  performance:
    max_search_threads: 0
    max_optimization_threads: 1

  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0.
    max_segment_size_kb: null
    memmap_threshold_kb: null
    indexing_threshold_kb: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1

  hnsw_index:
    m: 16
    ef_construct: 100
    full_scan_threshold_kb: 10000
    max_indexing_threads: 0
    on_disk: false
    payload_m: null

service:
  max_request_size_mb: 32
  max_workers: 0
  #host: 192.168.0.163
  host: 0.0.0.0
  http_port: 6433
  grpc_port: 6434
  enable_cors: true

cluster:
  enabled: true
  p2p:
    port: 6435
  consensus:
    tick_period_ms: 100

telemetry_disabled: false
