version: "3.7"

services:
  docker-registry-ml:
    image: registry:2.7
    container_name: docker-registry-ml
    hostname: docker-registry-ml
    ports:
     - ${REGISTRY_PORT}:5160
    networks:
      ml_registry_network:
        ipv4_address: ${IP_BACKEND}
    restart: always
    volumes:
    - "registry-data:${REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY}"
    - "./conf/:/etc/docker/registry/"
    - "./certs:/certs"
    - "./auth:/auth"
    env_file:
      - .env

  docker-registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: docker-registry-ui
    hostname: docker-registry-ml-ui
    restart: always
    networks:
      ml_registry_network:
        ipv4_address: ${IP_FRONTEND}
    ports:
      - "${UI_HTTP_PORT}:80"
      - "${UI_HTTPS_PORT}:443"
    environment:
      - NGINX_PROXY_HEADER_X_Forwarded_For=$$proxy_add_x_forwarded_for
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem
      - ./nginx/nginx.env:/etc/nginx/.env
    env_file:
      - .env
    depends_on:
      - docker-registry-ml

networks:
   ml_registry_network:
      external: true

volumes:
  registry-data: