# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:2.5.1
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_PROJ_DIR             - Base path to which all the files will be volumed.
#                                Default: .
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Default: ''
#
# Feel free to modify this file to suit your needs.
---
version: '3'
x-airflow-common:
  &airflow-common
  #image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.2}
  build:
    context: ../airflow
    dockerfile: Dockerfile
  environment:
    &airflow-common-env
    # Airflow User
    AIRFLOW_UID: '1000'
    AIRFLOW_GID: '0'

    # Airflow Base
    AIRFLOW_PROJ_DIR: ${AIRFLOW_BASE_MNT}
    AIRFLOW_HOME: ${AIRFLOW_BASE_MNT}
    AIRFLOW_BASE_MNT: ${AIRFLOW_BASE_MNT}

    ### Airflow Core
    AIRFLOW__CORE__DAGS_FOLDER: '${AIRFLOW_BASE_MNT}/dags'
    AIRFLOW__CORE__PLUGINS_FOLDER: '${AIRFLOW_BASE_MNT}/plugins'
    AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Istanbul
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres/airflow'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres/airflow'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__PARALLELISM: 4
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 2
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 30.0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    #AIRFLOW__CORE__HOSTNAME_CALLABLE: 'airflow.utils.net.get_host_ip_address'
    #AIRFLOW__CORE__HOSTNAME_CALLABLE: 'socket.getfqdn'

    ### Airflow Database
    AIRFLOW__LOAD__DEFAULT__CONNECTIONS: 'true'

    ### Airflow Logging
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: '${AIRFLOW_BASE_MNT}/logs'
    AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'
    AIRFLOW__LOGGING__LEVEL: 'INFO'
    AIRFLOW__LOGGING__ENCRPYT_S3_LOGS: 'true'

    ### Airflow API
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'

    ### Airflow Operators
    AIRFLOW__OPERATORS__DEFAULT_OWNER: 'airflow'
    AIRFLOW__OPERATORS__DEFAULT_CPUS: 1
    AIRFLOW__OPERATORS__DEFAULT_RAM: 512
    AIRFLOW__OPERATORS__DEFAULT_DISK: 512
    AIRFLOW__OPERATORS__DEFAULT_GPUS: 0
    AIRFLOW__OPERATORS__ALLOW_ILLEGAL_ARGUMENTS: 'false'

    ### Airflow Webserver
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'Europe/Istanbul'
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8086
    AIRFLOW__WEBSERVER__HOST: 0.0.0.0
    AIRFLOW__WEBSERVER__BASE_URL: 'http://localhost:8086'
    AIRFLOW__WEBSERVER__WORKERS: 4
    AIRFLOW__WEBSERVER__WORKER_CLASS: 'sync'

    # Airflow Admin init
    _AIRFLOW_DB_UPGRADE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    _AIRFLOW_WWW_USER_USERNAME: 'airflow'
    _AIRFLOW_WWW_USER_PASSWORD: 'ctolonml'

    ### Airflow Email
    AIRFLOW__EMAIL__EMAIL_BACKEND: 'airflow.utils.email.send_email_smtp'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: 'true'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: 'true'

    ### Airflow SMTP
    AIRFLOW__SMTP__SMTP_HOST: 'smtp.gmail.com'
    AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
    AIRFLOW__SMTP__SMTP_SSL: 'false'
    AIRFLOW__SMTP__SMTP_PORT: '587'
    AIRFLOW__EMAIL__FROM_EMAIL: "John Doe <johndoe@gmail.com>"
    AIRFLOW__SMTP__USER: 'johndoe@gmail.com'
    AIRFLOW__SMTP__PASSWORD: '<gmail-api-token>'
    AIRFLOW__SMTP__SMPT_TIMEOUT: 300
    AIRFLOW__SMTP__SMTP_RETRY_LIMIT: 10

    ### Airflow Scheduler
    #AIRFLOW__SCHEDULER__PARSING_PRE_IMPORT_MODULES: 'false'
    AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION: 'false'
    AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: '${AIRFLOW_BASE_MNT}/logs/scheduler'
  volumes:
    - ${AIRFLOW_BASE_MNT}/dags:${AIRFLOW_BASE_MNT}/dags
    - ${AIRFLOW_BASE_MNT}/logs:${AIRFLOW_BASE_MNT}/logs
    - ${AIRFLOW_BASE_MNT}/plugins:${AIRFLOW_BASE_MNT}/plugins
    - ${AIRFLOW_BASE_MNT}/dags/configs:${AIRFLOW_BASE_MNT}/dags/configs
    #- ./admin-scripts:/opt/admin-scripts
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    volumes:
      - postgres-db-volume:${POSTGRES_PATH}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    env_file:
      - .env
    networks:
      airflow-net:
        ipv4_address: 172.25.0.38

  airflow-webserver:
    <<: *airflow-common
    command: webserver -p 8086
    container_name: airflow-webserver
    environment:
      <<: *airflow-common-env
    #volumes:
    #- ./admin-scripts:/opt/admin-scripts
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8086/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      airflow-net:
        ipv4_address: 172.25.0.39
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    environment:
      <<: *airflow-common-env
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    ports:
      - 8793:8793
    networks:
      airflow-net:
        ipv4_address: 172.25.0.42
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        airflow_version_comparable=$$(ver $${airflow_version})
        min_airflow_version=2.2.0
        min_airflow_version_comparable=$$(ver $${min_airflow_version})
        if (( airflow_version_comparable < min_airflow_version_comparable )); then
          echo
          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
          echo
          exit 1
        fi
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
    container_name: airflow-init
    user: "0:0"
    networks:
      airflow-net:
        ipv4_address: 172.25.0.44
    volumes:
      - ${AIRFLOW_BASE_MNT}:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    container_name: airflow-cli
    networks:
      airflow-net:
        ipv4_address: 172.25.0.45
    command:
      - bash
      - -c
      - airflow

  # Reference: https://onedevblog.com/how-to-fix-a-permission-denied-when-using-dockeroperator-in-airflow/
  docker-proxy:
    image: bobrik/socat
    container_name: airflow-docker-proxy
    networks:
      airflow-net:
        ipv4_address: 172.25.0.64
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "${DP_PORT_HOST}:${DP_PORT_CNT}"
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH}
    restart: always
    healthcheck:
      test: ["CMD", "socat", "STDIO", "UNIX-CONNECT:/var/run/docker.sock"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
   airflow-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

volumes:
  postgres-db-volume: