# Jenkins DooD Approach.

networks:
  jenkins_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.90.0.0/24
          gateway: 172.90.0.1

version: '3'

services:

  # Jenkins Master
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: master-jenkins
    container_name: jenkins-controller
    networks:
      jenkins_net:
        ipv4_address: 172.90.0.2
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_backup:/tmp/backup/hudson
      #- /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "8085:8080"
      - "5015:5000"
      - "50015:50000"
    environment:
      #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --prefix=/jenkins
      - JAVA_OPTS=-Xms1536m -Xmx1536m

    user: jenkins
    restart: on-failure

  # Jenkins Agent
  agent:
    image: slave-jenkins
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: jenkins-agent
    user: root
    #privileged: true
    restart: on-failure
    networks:
      jenkins_net:
        ipv4_address: 172.90.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 22
    env_file:
      - .env
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnKjMXOLw3lgawZj756QY+kfWoHY6zMT7cIVnsSdPUL jenkins.
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JAVA_HOME=/opt/java/openjdk/bin/java
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    memswap_limit: 4096M