
version: '3.6'

networks:
  rabbitmq_net:
    external: true

services:
    rabbitmq-mysql:
        container_name: rabbitmq-mysql
        image: mysql:5.7
        restart: unless-stopped
        stdin_open: true
        tty: true
        environment:
          MYSQL_DATABASE: celery
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_ROOT_USER: admin
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
         - "3306:3306"
        entrypoint: # create db if not exist
          sh -c "
           echo 'CREATE DATABASE IF NOT EXISTS celery;' > /docker-entrypoint-initdb.d/init.sql;
           /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_general_ci "  
        volumes:
         - ./mysql-data/raw:/var/lib/mysql:rw # persistent volume
         - ./mysql-data/logs:/logs
         - ./mysql-data/conf.d:/etc/mysql/conf.d
         - ./conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf # config mysql server
#volumes:
#  mysql-data:
#    driver: local